from tests.tests_model.tests_functions.tests_bounds import TestsUCB
from tests.tests_model.tests_functions.tests_decision import TestsEGreedy
from tests.tests_model.tests_functions.tests_prediction import TestsMean
from tests.tests_model.tests_functions.tests_prediction import TestsStepSize
