[build-system]
requires = ["setuptools>=61", "wheel", "setuptools-git-versioning"]
build-backend = "setuptools.build_meta"

[project]
name = "bandit-agents"
dynamic = ["version"]
dependencies = [
  "numpy",
  "scipy"
]