version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: conda env create -f bandit_generator.yml
          name: CreateEnv
      - run:
          command: conda activate bandit_generator
          name: ActivateEnv
      - run:
          command: python -m unittest tests
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
