from tests.tests_model.tests_functions import TestsUCB
from tests.tests_model.tests_functions import TestsEGreedy
from tests.tests_model.tests_functions import TestsStepSize
from tests.tests_model.tests_functions import TestsMean