name: PR workflow
on:
  pull_request:
    types:
      - created
    branches:
      - master

jobs:
  run-unit-tests:
    environment: unittests env
    steps:
      - name: run unittests
        run: docker compose up --build unit-tests
