name: Publish on Pypi workflow
on:
  push:
    branches:
      - releases/**

jobs:
  publish-on-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: publish on pypi
        run: docker compose -f docker-compose.yml up --build publish-lib