name: Publish on Pypi workflow
on:
  push:
    branches:
      - releases/**

jobs:
  publish-on-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: publish on pypi
        run: docker compose up publish-lib